/* eslint-disable @next/next/no-page-custom-font */
/* eslint-disable @next/next/google-font-display */
/* eslint-disable react/no-children-prop */
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import QuickLinks from '@/components/QuickLinks'
import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'
import { Headers } from '@/components/Header'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        {/* <title>Codex - Welcome</title> */}
        <meta name="Codex is a content management system" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"></link>
        {/* <link rel="icon" href="" /> */}
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"></link>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" ></link>
      </Head>
      <Navbar />
        <main className={styles.main}>
          <Headers />
        </main>
        <QuickLinks />
        <Footer />
    </>
  )
}
