/* eslint-disable react/no-children-prop */
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import QuickLinks from '@/components/QuickLinks'
import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'
import { Headers } from '@/components/Header'
import MostPopular from '@/components/MostPopular'
import TechnicalCategories from '@/components/TechnicalCategories'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Codex - Welcome</title>
        <meta name="Codex is a content management system" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet"></link>
      </Head>
        <Navbar />
        <main className={styles.main}>
          <Headers />
        </main>
        <TechnicalCategories />
        <MostPopular />
        <QuickLinks />
        <Footer />
    </>
  )
}

