import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import QuickLinks from '@/components/QuickLinks'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Codex - Welcome</title>
        <meta name="Codex is a content management system" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="" />
      </Head>
        <main className={styles.main}>
          <div>
            Welcome to Codex
          </div>
        </main>
        <QuickLinks />
        <Footer />
    </>
  )
}
