import Navbar from "../components/Navbar";
import Head from "next/head";
import React, { useState } from "react";
import Footer from "../components/Footer";
import Articles from "./Main";
import LeftSideMenu from "../components/LeftSideMenu";
import RightSideMenu from "../components/RightSideMenu";

interface Props {
  hidden: string;
  element: JSX.Element;
}

export default function UserGuide(props: Props) {
  const { hidden, element } = props;
  const [isClassAdded, setIsClassAdded] = useState<boolean>(false);

  const handleClick = () => {
    setIsClassAdded(!isClassAdded);
    console.log(isClassAdded);
  };
  return (
    <>
      <Head>
        <title>Codex - User Guide</title>
        <meta
          name="Codex is a content management system"
          content="Generated by create next app"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
        />
      </Head>

      <Navbar />
      
      <LeftSideMenu hidden={""} />

      <main className="main-section">
        <div>
            <Articles />
            <RightSideMenu />
        </div>

        <Footer />
      </main>
    </>
  );
}
